application_name: OPC Modbus Gateway (prototype)
application_uri: urn:opc-modbus-gateway:prototype
product_uri: urn:opc-modbus-gateway:prototype-testkit
create_sample_keypair: true
certificate_path: own/cert.der
private_key_path: private/private.pem
certificate_validation:
  trust_client_certs: true
  check_time: true
pki_dir: ./pki
tcp_config:
  hello_timeout: 5
  host: 0.0.0.0
  port: 4841
limits:
  max_array_length: 100000
  max_string_length: 65535
  max_byte_string_length: 65535
  max_message_size: 327675
  max_chunk_count: 5
  send_buffer_size: 65535
  receive_buffer_size: 65535
  max_browse_continuation_points: 5000
  max_history_continuation_points: 500
  max_query_continuation_points: 500
  max_sessions: 20
  subscriptions:
    max_subscriptions_per_session: 100
    max_pending_publish_requests: 20
    max_publish_requests_per_subscription: 4
    min_sampling_interval_ms: 100
    min_publishing_interval_ms: 100
    max_keep_alive_count: 30000
    default_keep_alive_count: 10
    max_monitored_items_per_sub: 0
    max_monitored_item_queue_size: 10
    max_lifetime_count: 90000
    max_notifications_per_publish: 0
    max_queued_notifications: 20
  operational:
    max_nodes_per_translate_browse_paths_to_node_ids: 100
    max_nodes_per_read: 10000
    max_nodes_per_write: 10000
    max_nodes_per_method_call: 100
    max_nodes_per_browse: 1000
    max_nodes_per_register_nodes: 1000
    max_monitored_items_per_call: 1000
    max_nodes_per_history_read_data: 100
    max_nodes_per_history_read_events: 100
    max_nodes_per_history_update: 100
    max_references_per_browse_node: 1000
    max_node_descs_per_query: 100
    max_data_sets_query_return: 1000
    max_references_query_return: 100
    max_nodes_per_node_management: 1000
    max_references_per_references_management: 1000
    max_subscriptions_per_call: 10
locale_ids:
- en
user_tokens:
  sample_password_user:
    user: sample1
    pass: sample1pwd
    read_diagnostics: true
discovery_urls:
- opc.tcp://localhost:4841/
default_endpoint: null
endpoints:
  none:
    path: /
    security_policy: None
    security_mode: None
    security_level: 0
    password_security_policy: null
    user_token_ids:
    - ANONYMOUS
    - sample_password_user
  basic256sha256_sign_encrypt:
    path: /
    security_policy: Basic256Sha256
    security_mode: SignAndEncrypt
    security_level: 14
    password_security_policy: null
    user_token_ids:
    - ANONYMOUS
    - sample_password_user
